apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app: {{ .Values.metadata.labels.app }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.metadata.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.labels.app }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image.name }}:{{ .Values.container.image.tag }}
          imagePullPolicy: {{ .Values.container.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
              protocol: {{ .Values.container.protocol }}

