metadata:
  namespace: skaffold-example
  labels:
    app: skaffold-example
deployment:
  replicaCount: 1
  namespace: skaffold-example
  name: skaffold-example
container:
  name: skaffold-example
  image:
    name: robbyra98/argo-image-updater-poc
    tag: 0.0.0
    pullPolicy: IfNotPresent
  port: 8080
  protocol: TCP
service:
  name: skaffold-example
  type: NodePort
  targetPort: 8080

